#CONFIGURACION DE LA BASE DE DATOS
#CONEXION A NUESTRA BASE DE DATOS
spring.datasource.url=jdbc:postgresql://localhost:5432/restaurant_bd
#NOMBRE DE NUESTRA APP (LOGS,MICROSERVICIOS,ETC)
spring.application.name=restaurant-order-system
#USUARIO DEL CUAL NOS CONECTAMOS
spring.datasource.username=postgres
#CONTRASEÑA DE ACCESO
spring.datasource.password=admin123
#CONEXION QUE PERMITE QUE NUESTRO JAVA PUEDA COMUNICARSE EB ESTE CASO CON POSTGRESQL
spring.datasource.driver-class-name=org.postgresql.Driver
#CREACION DE NUESTRA TABLA EN MODO UPDATE PARA CREAR/ACTUALIZAR
spring.jpa.hibernate.ddl-auto=update
#VISUALIZAR SQL EN CONSOLA
spring.jpa.show-sql=true
#ORDENA NUESTRO SQL
spring.jpa.properties.hibernate.format_sql=true
#GENERA LA COMPATIBLIDAD CON EL MOTOR
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
#PUERTO DONDE CORREO EL SERVIDOR
server.port=8081